import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
const outfit = Outfit({ subsets: ["latin"] });
import { Toaster } from "@/packages/ui/toaster";
import { ThemeProvider } from "@/packages/ui/theme/theme-provider";
import { AuthContextProvider } from "@/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ThemeProvider attribute="class" defaultTheme="light-black">
          <AuthContextProvider>
            {children} <Toaster />
          </AuthContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
