import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
const outfit = Outfit({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/ui/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children} <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
