#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check tsconfig standards
npm run check-types ||
(
    echo '❌ Failed Type check. ❌'
    false;
)

# If everything passes... Now we can commit
echo '✅ Eveything looks good ✅'
